---
server:
  port: 8080
  contextPath: /SpringBootCRUDApp
---
 mail:
    host: smtp.gmail.com
    port: 587
    username: neven95jovic@gmail.com
    password: Paperino1993
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
---
 
---
spring:
  
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/isa-2018?useSSL=false
    username: hbstudent
    password: hbstudent
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
